language: python
python:
- '2.7'
script:
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: archerysec
  password:
    secure: GnBwtlvfndVfij1BjA5zTEzpXQQ3V4zvOFFcadwd8wzFm9AD05o5NMH1npHNcfc7tWSnYHc6ahWBKcrAwRNeFa9w2GeBCt5VOh7hu7PWFf5dIk414LokjtKKJF7g9oC6PGs98zQdWVRl3hWd2yRjsONo17EkgumbcmAz5+iQUQhN1CeKfegfaoaTYegXsZK+P63LQp5dv/v9+m6IzbPf6su5EqWWZ0pJ1tqIyujH7UNDIZVJrKh46GPpIEbEVpmdfrMPJX4vB88VUiHGMzDz6x1XFDcOigoe7E1XhQvI8FFKXCFN1rpGUzna3upLqoqnzw5AZdC/WGczl+x51Q8PhwXWXxlAaQySgr3+xWKhsYwyWVA/JBPPX/yUvIycZ//3Hc2pRI2iCLnAOaOBo7cnOqc2hVV/igI7m7n9wHATdtYMbDwFJwFtjwGAgj2AEyrKsL1xqSyVAGYMKMYh5lPPMuX2SJWsSLg+QoVTdyZFc75gs6ofqTCQrHmZFxjKY9/CdBC77+EPvLcI5oDo4Mdsy3QZJl8AauZ3uLD9SxQm9f+SRTdtg4cPgpofYboq7J+3uyr5hYaLOl9nH9wdVCQXiwv4sbj25yrdIIsT/7d/BWN83eKhU9FVEQ9r/6Qm1GO9nnB38c0dYeu08UlyNa93FlcQxvnb9bFtyqru4r8RvSY=
  on:
    distributions: sdist bdist_wheel
    repo: anandtiwarics/python-burp-rest-api