language: python
python:
- '2.7'
script:
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: archerysec
  password:
    secure: gAZKCn2ZdJnbdxorv8jwPAXgCtk/84311f5mFtOb3lG8bMnDfhJvJd4esrYviLb1XSwZTDz4q8yNM4OVah22dO35dky96/1aEBtlg1iPprhGn24Ngo/c8Cj29kxlil4/akum96i3fhHtCm8Lfc3RixCy5d3aKdANffjvcqEYXD9wtwGLu+cDpYelj6FUn2Mt+JNxjwc3cxxcZ4iY0x7PFrrgviZxeruN7JguHqX/o+EocGPWiilQ+PEKG9uZO3cS4rqVTV7UQKjdSPgnvfPEBpWbN6UBEva8OXXPRIiCDAwnkk2stEhoE8pqEkSS0uSflP8Vqp4G+VkoEuU3oxTVaTusDiaJ9RTJoTqBo/vaH8bivrHoqLcOP1fB5r95XdwdOAgdpDZ4E5JHW+9VehQqwIvzT0BIMrB+JYGLvrwTMHM8cRxM2jOtdD+uhGi9lvYQ8PFI614YI1d1ZVAY1PBchjGQRbEKxgNEp2AEXWc9pwg/W2q0mTGp7AWQAFLgutGh/o/0WUfl5KJKnlvAy1/dXsnFF2yOkpffL5kO3V3LZc8jcFJ0Jrtdxb5fLgMJ8/L7eWZAx61Wl7FDDdrwIvk9vwzDBaYDQV6Ikg/pBWMBOEtqLpZ8Lmuthbevxp5Putk7r462pgeJuSr8YE10oHc63fy6NcseS5O87LE2yehXvYo=
  on:
    distributions: sdist bdist_wheel
    repo: anandtiwarics/python-burp-rest-api