language: python
python:
- '2.7'
script:
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  user: archerysec
  password:
    secure: bdWl7C19BCLXxpMsv7GZw6Q1TiKmEdoTzo7mjRCTxR+eB0XXh4ryXnPnvmVZxaaDDnRvuOWUd0g+xDPYA61m1F/Cg44Z93pi3y2AKkL+/Vzku/xb5SmwZ9HpRPermMtCOpyNuHshIVXC5u5ChtA/VcdEN3EO8wofdkSmWG8QtP34OD669q775tfLF0ZQg7Lfm5/zXVTgKl8RnkMY8ls8QkMxZzPoto9L0/F1l5zRwT8cx7Bwcj9NBiwL6UFxUcqZ7qZQVZp43l9CoV4Swt+EQ6O9PxVFhPrLFPGo6lr/dp/d0uOvOJQyTK0BLEnktLdvw0nY8+oxDbfJsLHDU7LXy8gAP+d4ChVIuiJJjdMkrBRunTWKeOJsrObU+uFPsCHh+F0lzpQ/mTJEIkUcC7E+C8jNjuVhik5QXOfe3OUzcNK8iVIgQyuQakahkQCl5rzSOkLMPkTv44Nl2H7D27R/MMSX6bC967zHP4ee/29fZGKexVeoxX9rQTfyDMLGL9Hk9z7k5zN+zEplofzjiHo98wH/ncyIUh5s1Sh9I+3BAEZe+PAHf+o9nivuMwAsH9s2ktBGQdqC8t4ZqeZwJ750rvZMHNcK0VyCGe7miEvD1u4JFIYyeI8jjW9PVsjCoaFY+7vRXmLNcXLOa0GK6zanWM1t/APLH6m9UobhvJJEDAQ=
  on:
    distributions: sdist bdist_wheel
    repo: anandtiwarics/python-burp-rest-api